/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import models.Playstation;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import GUI.*;

public class Updatepeminjam extends javax.swing.JFrame {

    Playstation Ps;
    String id;
    String nama;
    String durasi;
    String alamat;
    String ps;
    Main mainFrame;

    public Updatepeminjam(Main mainFrame, String id, String nama, String durasi, String alamat, String ps) throws ClassNotFoundException, SQLException {
        Ps = new Playstation();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        formNP.setBackground(new java.awt.Color(0, 0, 0, 1));
        formDp.setBackground(new java.awt.Color(0, 0, 0, 1));
        formAp.setBackground(new java.awt.Color(0, 0, 0, 1));

        this.id = id;
        this.formNP.setText(nama);
        this.formDp.setText(durasi);
        this.formAp.setText(alamat);
        this.formJp.setSelectedItem(ps);

        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formNP = new javax.swing.JTextField();
        formDp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        formAp = new javax.swing.JTextField();
        upData = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formJp = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formNP.setBackground(new java.awt.Color(242, 242, 242));
        formNP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formNP.setForeground(new java.awt.Color(255, 255, 255));
        formNP.setBorder(null);
        formNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNPActionPerformed(evt);
            }
        });
        getContentPane().add(formNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 230, 20));
        formNP.getAccessibleContext().setAccessibleDescription("");

        formDp.setBackground(new java.awt.Color(242, 242, 242));
        formDp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formDp.setForeground(new java.awt.Color(255, 255, 255));
        formDp.setBorder(null);
        formDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDpActionPerformed(evt);
            }
        });
        getContentPane().add(formDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 230, 20));

        jLabel1.setFont(new java.awt.Font("Inter Extra Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ubah Peminjam");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 19, -1, 30));

        formAp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formAp.setForeground(new java.awt.Color(255, 255, 255));
        formAp.setBorder(null);
        formAp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        formAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formApActionPerformed(evt);
            }
        });
        getContentPane().add(formAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 230, 20));

        upData.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        upData.setText("Ubah");
        upData.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        upData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upDataMouseEntered(evt);
            }
        });
        upData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDataActionPerformed(evt);
            }
        });
        getContentPane().add(upData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 92, 30));

        cancel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 92, 30));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Nama Peminjam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukkan Durasi Peminjaman");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Masukkan Alamat Peminjam");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pilih Jenis Playstation");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 157, -1));

        formJp.setBackground(new java.awt.Color(242, 242, 242));
        formJp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formJp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playstation 3", "Playstation 4", "Playstation 5" }));
        getContentPane().add(formJp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 230, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 230, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 230, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/playstation-logo-background-hd-wallpaper-uhdpaper.com-118@0@e.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNPActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void formDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDpActionPerformed

    private void formApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formApActionPerformed

    private void upDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upDataActionPerformed

    private void upDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_upDataMouseEntered

    private void upDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDataMouseClicked
        try {
            String hb = formNP.getText();
            String jb = formDp.getText();
            String kb = formAp.getText();
            String ps = formJp.getSelectedItem().toString();

            try {
                if (Integer.parseInt(jb) > 0) {
                    Ps.update(Integer.parseInt(this.id), hb, jb, kb, ps);
                    this.mainFrame.showData();
                    JOptionPane.showMessageDialog(null, "UBAH DATA BERHASIL");
                } else {
                    JOptionPane.showMessageDialog(null, "Mohon masukkan durasi yang benar");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Mohon masukkan durasi yang benar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "UBAH DATA GAGAL");
//            try {
//                new Updatepeminjam().setVisible(true);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(Updatepeminjam.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(Updatepeminjam.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_upDataMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        try {
            int jawab = JOptionPane.showOptionDialog(this,
                    "Apakah anda yakin ingin Cancel?",
                    "Cancel",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, null, null);

            if (jawab == JOptionPane.YES_OPTION) {
                new Main().setVisible(true);
                this.dispose();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addpeminjam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addpeminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField formAp;
    private javax.swing.JTextField formDp;
    private javax.swing.JComboBox<String> formJp;
    private javax.swing.JTextField formNP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton upData;
    // End of variables declaration//GEN-END:variables
}
